server:
  port: 9005      # 端口号

eureka:
  server:
    enable-self-preservation: false
  instance:
    hostname: localhost
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 2
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://127.0.0.1:9000/eureka
    registry-fetch-interval-seconds: 1

spring:
  application:
    name: eureka

