server:
  port: 9100

#这样就把第三方服务,注册进了eureka,接着可以使用feign调用第三方模块功能,也可以使用zool进行调用
eureka:
  instance:
    hostname: localhost
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 2
  client:
    service-url:
      defaultZone: http://localhost:9005/eureka/,http://localhost:9000/eureka
    registry-fetch-interval-seconds: 1


#指定服务的名称
spring:
#  cloud:
#    stream:
#      bindings:
#        mLine: # 消息队列名
#          group: invokeChain #可以任意指定 ,这样就不会重复消费了
  rabbitmq: #绑定rabbitmq
    host: 192.168.169.135
    port: 5672
    username: guest
    password: guest
    virtual-host: /mLine #设定消息队列
  sleuth:
    sampler:
      probability: 1   # 百分之多少的sleuth信息需要输出到zipkin中
  zipkin:
    base-url: http://192.168.169.135:9411/  # 指定zipkin的地址
    sender:
      type: rabbit

  application:
    name: node-a


logging:
  level:
    org.springframework.web.servlet.DispatcherServlet: DEBUG


